name = "ferry"
compatibility_date = "2024-01-01"

# Cloudflare Pages build output directory
pages_build_output_dir = "dist/apps/ferry"

[build]
install = "npm install --force"
command = "npm run build"
cwd = "."

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

